# Generated by Django 3.1.4 on 2020-12-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0002_foodimage_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='serving',
            field=models.FloatField(),
        ),
    ]
